# This workflow will install Python dependencies, run tests, calculate coverage, and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    # Define environment variables here using GitHub secrets
    env:
      LOG_FILE: ${{ secrets.LOG_FILE }}
      HISTORY_FILENAME: ${{ secrets.HISTORY_FILENAME }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install all dependencies from requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-fail-under=100  # Set to fail if coverage is below 100%

    - name: Generate coverage report
      run: |
        coverage report  # Prints a summary of the coverage report to the console
        coverage xml     # Generates an XML report for more detailed analysis, if needed
